// Problem catalogue.  In production these would come from Postgres
// (see database/schema.sql); for the demo we keep them as a static
// in-memory list so the platform is runnable without a database.
//
// NOTE: `starter` holds a STUB (input scaffold + TODO), never the answer.
// The worked solution lives in `solution` and is shown only in the locked
// "Solution" tab.  All `test_cases[].expected` values were produced by
// running the reference solution under Python, so the judge returns AC
// for `solution` on every problem.  (Generated by tooling/cs_gen.py.)

export type CheckerType = "exact" | "trimmed" | "numeric_eps" | "custom_checker";
export type Difficulty = "Easy" | "Medium" | "Hard";
export type LanguageCode = "python3" | "cpp17" | "java17" | "node18" | "go121";

export interface TestCase {
  seq: number;
  input: string;
  expected: string;
  is_sample: boolean;
  label?: string;
}

export interface Example {
  input: string;
  output: string;
  explanation?: string;
}

export interface Complexity {
  time: string;
  space: string;
}

export interface Problem {
  slug: string;
  problem_id: number;
  title: string;
  difficulty: Difficulty;
  tags: string[];
  description: string;
  constraints: string[];
  examples: Example[];
  hints: string[];
  editorial: string;
  approach: string;                       // markdown, shown in Solution tab
  complexity: Complexity;
  company_tags: string[];
  frequency: number;                      // 0-100, "how often asked"
  related: string[];                      // related problem slugs
  time_limit_ms: number;
  memory_limit_mb: number;
  checker_type: CheckerType;
  checker_eps?: number;
  starter: Partial<Record<LanguageCode, string>>;   // STUB, never the answer
  solution: Partial<Record<LanguageCode, string>>;  // reference solution
  test_cases: TestCase[];
  acceptance_rate: number;
  likes: number;
  dislikes: number;
}

export interface ProblemList {
  slug: string;
  name: string;
  description: string;
  icon: string;
  problem_slugs: string[];
}

export const ALL_TAGS = [
  "Array", "String", "Hash Table", "Math", "Two Pointers",
  "Dynamic Programming", "Binary Search", "Sorting", "Greedy",
  "Stack", "Linked List", "Tree", "Recursion",
] as const;

export const LANGUAGES: { code: LanguageCode; label: string }[] = [
  { code: "python3", label: "Python 3" },
  { code: "cpp17",   label: "C++ 17"    },
  { code: "java17",  label: "Java 17"   },
  { code: "node18",  label: "JavaScript"},
  { code: "go121",   label: "Go"        },
];

// Languages the local judge can actually execute.  Others surface as
// SE ("language not wired in demo") so the UI still lets you pick them.
export const RUNNABLE_LANGUAGES: Set<LanguageCode> = new Set(["python3"]);

export const GENERIC_STUB: Record<LanguageCode, string> = {
  "python3": "# read input from stdin and print your answer\n# TODO: implement\n",
  "cpp17": "#include <bits/stdc++.h>\nusing namespace std;\nint main(){\n    // TODO: read stdin, print answer\n    return 0;\n}\n",
  "java17": "import java.util.*;\npublic class Main {\n  public static void main(String[] a) {\n    Scanner s = new Scanner(System.in);\n    // TODO: read stdin, print answer\n  }\n}\n",
  "node18": "const data = require('fs').readFileSync(0, 'utf8');\n// TODO: parse `data` and print your answer\n",
  "go121": "package main\nimport (\"bufio\"; \"fmt\"; \"os\")\nfunc main(){\n    r := bufio.NewReader(os.Stdin)\n    _ = r\n    // TODO: read stdin, print answer\n    fmt.Print(\"\")\n}\n"
};

export const PROBLEMS: Problem[] = [
  {
    "slug": "two-sum-int",
    "problem_id": 1,
    "title": "Two Sum (Integers)",
    "difficulty": "Easy",
    "tags": [
      "Array",
      "Hash Table",
      "Math"
    ],
    "description": "Given two integers `a` and `b` on a single line separated by a space, print their sum.",
    "constraints": [
      "-10^9 ≤ a, b ≤ 10^9",
      "The result fits in a 64-bit signed integer."
    ],
    "examples": [
      {
        "input": "2 3",
        "output": "5",
        "explanation": "2 + 3 = 5"
      },
      {
        "input": "-5 10",
        "output": "5",
        "explanation": "-5 + 10 = 5"
      }
    ],
    "hints": [
      "Read the whole line and split it on the space.",
      "`a, b = map(int, input().split())` parses both integers at once."
    ],
    "editorial": "Parse two integers from a single line, add them, and print. The point is to confirm the judge's stdin/stdout conventions before tackling harder problems.",
    "approach": "## Idea\n\nThis problem asks for the sum of two integers given on a single line. The only real work is parsing the input correctly and then performing one arithmetic operation.\n\n## Steps\n\n- Read the single line of input.\n- Split it on whitespace into two tokens and convert each to an `int` with `map(int, ...)`.\n- Add the two values and print the result.\n\n```python\na, b = map(int, input().split())\nprint(a + b)\n```\n\n## Notes\n\nPython integers are arbitrary precision, so even the extreme inputs (`1e9 + 1e9 = 2e9`, which exceeds 32-bit signed range) are handled natively without any overflow concerns. Negative numbers, zeros, and mixed-sign operands all work through the same path because `int()` parses a leading minus sign and `+` handles signed arithmetic directly. There are no edge cases beyond ensuring exactly two tokens are read.",
    "complexity": {
      "time": "O(1)",
      "space": "O(1)"
    },
    "company_tags": [
      "Amazon",
      "Google",
      "Microsoft",
      "Apple"
    ],
    "frequency": 62,
    "related": [
      "sum-of-list",
      "max-of-list",
      "factorial"
    ],
    "time_limit_ms": 2000,
    "memory_limit_mb": 256,
    "checker_type": "trimmed",
    "starter": {
      "python3": "a, b = map(int, input().split())\n# TODO: compute the sum of a and b\nprint(\"\")\n"
    },
    "solution": {
      "python3": "a, b = map(int, input().split())\nprint(a + b)\n"
    },
    "test_cases": [
      {
        "seq": 1,
        "input": "2 3\n",
        "expected": "5\n",
        "is_sample": true,
        "label": "Basic positive sum"
      },
      {
        "seq": 2,
        "input": "-5 10\n",
        "expected": "5\n",
        "is_sample": true,
        "label": "Negative and positive"
      },
      {
        "seq": 3,
        "input": "0 0\n",
        "expected": "0\n",
        "is_sample": false,
        "label": "Zero boundary"
      },
      {
        "seq": 4,
        "input": "1000000000 1000000000\n",
        "expected": "2000000000\n",
        "is_sample": false,
        "label": "Max positive boundary"
      },
      {
        "seq": 5,
        "input": "-1000000000 -1000000000\n",
        "expected": "-2000000000\n",
        "is_sample": false,
        "label": "Min negative boundary"
      },
      {
        "seq": 6,
        "input": "1000000000 -1000000000\n",
        "expected": "0\n",
        "is_sample": false,
        "label": "Opposite extremes cancel"
      },
      {
        "seq": 7,
        "input": "-7 -8\n",
        "expected": "-15\n",
        "is_sample": false,
        "label": "Both negative"
      },
      {
        "seq": 8,
        "input": "123456789 987654321\n",
        "expected": "1111111110\n",
        "is_sample": false,
        "label": "Large typical values"
      },
      {
        "seq": 9,
        "input": "-1000000000 1\n",
        "expected": "-999999999\n",
        "is_sample": false,
        "label": "Min plus one"
      },
      {
        "seq": 10,
        "input": "5 -5\n",
        "expected": "0\n",
        "is_sample": false,
        "label": "Sum to zero"
      }
    ],
    "acceptance_rate": 0.91,
    "likes": 1240,
    "dislikes": 18
  },
  {
    "slug": "reverse-string",
    "problem_id": 2,
    "title": "Reverse a String",
    "difficulty": "Easy",
    "tags": [
      "String",
      "Two Pointers"
    ],
    "description": "Read a single line containing a string `s` and print it reversed.",
    "constraints": [
      "1 ≤ |s| ≤ 10^5",
      "`s` contains printable ASCII characters and no spaces."
    ],
    "examples": [
      {
        "input": "hello",
        "output": "olleh"
      },
      {
        "input": "abcdef",
        "output": "fedcba"
      }
    ],
    "hints": [
      "Python slicing reverses in one step: `s[::-1]`.",
      "Or walk two pointers inward from both ends, swapping as you go."
    ],
    "editorial": "`s[::-1]` builds the reversed string in O(n). A constant-extra-space alternative swaps characters with two pointers moving toward the middle.",
    "approach": "## Idea\n\nWe are given a single string `s` and must print it reversed. The cleanest way in Python is to use slicing with a negative step.\n\n```python\ns = input()\nprint(s[::-1])\n```\n\nThe slice `s[::-1]` walks the string from the last character to the first, producing a new reversed string in one pass. This is concise, idiomatic, and runs in linear time.\n\n## Two-pointer alternative\n\nIf you wanted to do it manually (as the \"Two Pointers\" tag suggests), convert the string to a list, place one pointer at the start and one at the end, swap the two characters, then move the pointers toward each other until they meet:\n\n- `i = 0`, `j = len(s) - 1`\n- while `i < j`: swap `s[i]` and `s[j]`, then `i += 1`, `j -= 1`\n\nBoth approaches are O(n) time. The slice version allocates a new string; the in-place two-pointer version on a list uses O(n) extra space for the list but only O(1) beyond that for the swaps. Either is fast enough for the 100000-character limit.",
    "complexity": {
      "time": "O(n)",
      "space": "O(n)"
    },
    "company_tags": [
      "Amazon",
      "Microsoft",
      "Google",
      "Apple",
      "Adobe"
    ],
    "frequency": 72,
    "related": [
      "palindrome-check",
      "anagram-check",
      "sum-of-list"
    ],
    "time_limit_ms": 1000,
    "memory_limit_mb": 128,
    "checker_type": "trimmed",
    "starter": {
      "python3": "s = input()\n# TODO: reverse the string and print it\nprint(\"\")\n"
    },
    "solution": {
      "python3": "s = input()\nprint(s[::-1])\n"
    },
    "test_cases": [
      {
        "seq": 1,
        "input": "hello\n",
        "expected": "olleh\n",
        "is_sample": true,
        "label": "Simple word"
      },
      {
        "seq": 2,
        "input": "abcdef\n",
        "expected": "fedcba\n",
        "is_sample": true,
        "label": "Ordered letters"
      },
      {
        "seq": 3,
        "input": "a\n",
        "expected": "a\n",
        "is_sample": false,
        "label": "Minimal single char"
      },
      {
        "seq": 4,
        "input": "racecar\n",
        "expected": "racecar\n",
        "is_sample": false,
        "label": "Palindrome unchanged"
      },
      {
        "seq": 5,
        "input": "OpenAI123\n",
        "expected": "321IAnepO\n",
        "is_sample": false,
        "label": "Mixed letters and digits"
      },
      {
        "seq": 6,
        "input": "!@#$%^&*()\n",
        "expected": ")(*&^%$#@!\n",
        "is_sample": false,
        "label": "Special characters"
      },
      {
        "seq": 7,
        "input": "aaaa\n",
        "expected": "aaaa\n",
        "is_sample": false,
        "label": "Repeated characters"
      },
      {
        "seq": 8,
        "input": "Ab\n",
        "expected": "bA\n",
        "is_sample": false,
        "label": "Case sensitivity"
      },
      {
        "seq": 9,
        "input": "12345\n",
        "expected": "54321\n",
        "is_sample": false,
        "label": "All digits"
      },
      {
        "seq": 10,
        "input": "zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz\n",
        "expected": "zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz\n",
        "is_sample": false,
        "label": "Long run of one character"
      },
      {
        "seq": 11,
        "input": "AbcDef_123-XYZ\n",
        "expected": "ZYX-321_feDcbA\n",
        "is_sample": false,
        "label": "Mixed printable with underscore/dash"
      }
    ],
    "acceptance_rate": 0.82,
    "likes": 980,
    "dislikes": 22
  },
  {
    "slug": "sum-of-list",
    "problem_id": 3,
    "title": "Sum of a List",
    "difficulty": "Easy",
    "tags": [
      "Array",
      "Math"
    ],
    "description": "The first line contains `N`. The second line contains `N` space-separated integers. Print their sum.",
    "constraints": [
      "1 ≤ N ≤ 10^5",
      "-10^9 ≤ a[i] ≤ 10^9"
    ],
    "examples": [
      {
        "input": "3\n1 2 3",
        "output": "6",
        "explanation": "1 + 2 + 3 = 6"
      },
      {
        "input": "5\n10 20 30 40 50",
        "output": "150"
      }
    ],
    "hints": [
      "`sum(map(int, input().split()))` does it in one pass.",
      "Read and discard the first line (N); you only need the second."
    ],
    "editorial": "Stream the integers through `map(int, ...)` straight into `sum`, avoiding an intermediate list. Python's arbitrary-precision ints mean the ~10^14 worst-case total never overflows.",
    "approach": "## Idea\n\nWe are given a count `N` on the first line and `N` space-separated integers on the second line. The task is simply to add them all together and print the total. Because Python integers are arbitrary precision, there is no risk of overflow even when every value is near the bounds (`N` up to 1e5 and each value up to 1e9, so the sum can reach about 1e14 in magnitude).\n\n## Steps\n\n- Read the first line (the count `N`). It is only needed to know how many numbers to expect; once you have parsed the second line you can ignore it.\n- Read the second line, split it on whitespace, and convert each token to an `int`.\n- Accumulate the running total and print it.\n\nIn Python this collapses to a single pass: `sum(map(int, input().split()))`. The `map` lazily converts each token, and `sum` adds them as it goes, so no intermediate list is required.\n\n## Why it is efficient\n\nEach integer is read and added exactly once, giving linear `O(n)` time. Using `map` with `sum` avoids materializing a separate list, keeping extra space at `O(1)` beyond the input buffer. For the maximum input of 100,000 numbers this runs comfortably within the 2-second limit.",
    "complexity": {
      "time": "O(n)",
      "space": "O(1)"
    },
    "company_tags": [
      "Amazon",
      "Google",
      "Microsoft",
      "Meta"
    ],
    "frequency": 42,
    "related": [
      "max-of-list",
      "two-sum-int",
      "factorial"
    ],
    "time_limit_ms": 2000,
    "memory_limit_mb": 256,
    "checker_type": "trimmed",
    "starter": {
      "python3": "n = int(input())\nnums = list(map(int, input().split()))\n# TODO: compute the sum of nums and print it\nprint(\"\")\n"
    },
    "solution": {
      "python3": "input()\nprint(sum(map(int, input().split())))\n"
    },
    "test_cases": [
      {
        "seq": 1,
        "input": "3\n1 2 3\n",
        "expected": "6\n",
        "is_sample": true,
        "label": "Basic three positives"
      },
      {
        "seq": 2,
        "input": "5\n10 20 30 40 50\n",
        "expected": "150\n",
        "is_sample": true,
        "label": "Five round numbers"
      },
      {
        "seq": 3,
        "input": "1\n0\n",
        "expected": "0\n",
        "is_sample": false,
        "label": "Minimal: single zero"
      },
      {
        "seq": 4,
        "input": "1\n1000000000\n",
        "expected": "1000000000\n",
        "is_sample": false,
        "label": "Single max-value element"
      },
      {
        "seq": 5,
        "input": "4\n-5 -10 -15 -20\n",
        "expected": "-50\n",
        "is_sample": false,
        "label": "All negative"
      },
      {
        "seq": 6,
        "input": "6\n-100 100 -50 50 -25 25\n",
        "expected": "0\n",
        "is_sample": false,
        "label": "Mixed signs cancel"
      },
      {
        "seq": 7,
        "input": "5\n7 7 7 7 7\n",
        "expected": "35\n",
        "is_sample": false,
        "label": "Duplicate values"
      },
      {
        "seq": 8,
        "input": "2\n-1000000000 -1000000000\n",
        "expected": "-2000000000\n",
        "is_sample": false,
        "label": "Negative boundary"
      },
      {
        "seq": 9,
        "input": "3\n1000000000 1000000000 1000000000\n",
        "expected": "3000000000\n",
        "is_sample": false,
        "label": "Sum exceeds 32-bit range"
      },
      {
        "seq": 10,
        "input": "100\n1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96 97 98 99 100\n",
        "expected": "5050\n",
        "is_sample": false,
        "label": "100 elements (1..100) typical"
      },
      {
        "seq": 11,
        "input": "50\n-1000000000 -1000000000 -1000000000 -1000000000 -1000000000 -1000000000 -1000000000 -1000000000 -1000000000 -1000000000 -1000000000 -1000000000 -1000000000 -1000000000 -1000000000 -1000000000 -1000000000 -1000000000 -1000000000 -1000000000 -1000000000 -1000000000 -1000000000 -1000000000 -1000000000 -1000000000 -1000000000 -1000000000 -1000000000 -1000000000 -1000000000 -1000000000 -1000000000 -1000000000 -1000000000 -1000000000 -1000000000 -1000000000 -1000000000 -1000000000 -1000000000 -1000000000 -1000000000 -1000000000 -1000000000 -1000000000 -1000000000 -1000000000 -1000000000 -1000000000\n",
        "expected": "-50000000000\n",
        "is_sample": false,
        "label": "50 large-magnitude negatives"
      }
    ],
    "acceptance_rate": 0.88,
    "likes": 612,
    "dislikes": 8
  },
  {
    "slug": "fizz-buzz",
    "problem_id": 4,
    "title": "FizzBuzz",
    "difficulty": "Easy",
    "tags": [
      "String",
      "Math"
    ],
    "description": "Print the integers from 1 to `N`, one per line. Replace multiples of 3 with `Fizz`, multiples of 5 with `Buzz`, and multiples of both with `FizzBuzz`.",
    "constraints": [
      "1 ≤ N ≤ 10^5"
    ],
    "examples": [
      {
        "input": "5",
        "output": "1\n2\nFizz\n4\nBuzz"
      },
      {
        "input": "3",
        "output": "1\n2\nFizz"
      }
    ],
    "hints": [
      "Test `i % 15 == 0` **before** `% 3` and `% 5`.",
      "Collect lines in a list and emit them with one `print('\\n'.join(...))`."
    ],
    "editorial": "Order matters: check divisibility by 15 first, then 3, then 5, else the number. Buffer all lines and print once to avoid 10^5 separate print calls.",
    "approach": "## Idea\n\nThe classic FizzBuzz problem asks us to walk the integers `1..N` and, for each one, decide what to print based on divisibility:\n\n- divisible by both 3 and 5 (i.e. by 15) -> `FizzBuzz`\n- divisible by 3 only -> `Fizz`\n- divisible by 5 only -> `Buzz`\n- otherwise -> the number itself\n\nThe single most important detail is **ordering the checks correctly**. You must test the `% 15 == 0` (both) condition *first*. If you check `% 3` or `% 5` before the combined case, a multiple of 15 such as 15 or 30 will be caught by the earlier branch and incorrectly print `Fizz` or `Buzz` instead of `FizzBuzz`.\n\n## Implementation\n\n```python\nn = int(input())\nout = []\nfor i in range(1, n + 1):\n    if i % 15 == 0:\n        out.append('FizzBuzz')\n    elif i % 3 == 0:\n        out.append('Fizz')\n    elif i % 5 == 0:\n        out.append('Buzz')\n    else:\n        out.append(str(i))\nprint('\\n'.join(out))\n```\n\nBecause `N` can be as large as `1e5`, we accumulate every line into a list and emit it all at once with a single `'\\n'.join(...)` followed by one `print`. This avoids the per-call overhead of calling `print` 100000 separate times, which is noticeably slower and risks brushing up against the time limit on a busy judge. The checker is \"trimmed\", so trailing whitespace per line does not matter, but each value still belongs on its own line.",
    "complexity": {
      "time": "O(n)",
      "space": "O(n)"
    },
    "company_tags": [
      "Amazon",
      "Microsoft",
      "Google",
      "Bloomberg",
      "Adobe"
    ],
    "frequency": 72,
    "related": [
      "sum-of-list",
      "max-of-list",
      "factorial"
    ],
    "time_limit_ms": 2000,
    "memory_limit_mb": 256,
    "checker_type": "trimmed",
    "starter": {
      "python3": "n = int(input())\n# TODO: build the FizzBuzz sequence for numbers 1..n and print one per line\nprint(\"\")\n"
    },
    "solution": {
      "python3": "n = int(input())\nout = []\nfor i in range(1, n + 1):\n    if i % 15 == 0:\n        out.append('FizzBuzz')\n    elif i % 3 == 0:\n        out.append('Fizz')\n    elif i % 5 == 0:\n        out.append('Buzz')\n    else:\n        out.append(str(i))\nprint('\\n'.join(out))\n"
    },
    "test_cases": [
      {
        "seq": 1,
        "input": "5\n",
        "expected": "1\n2\nFizz\n4\nBuzz\n",
        "is_sample": true,
        "label": "First Fizz and Buzz"
      },
      {
        "seq": 2,
        "input": "15\n",
        "expected": "1\n2\nFizz\n4\nBuzz\nFizz\n7\n8\nFizz\nBuzz\n11\nFizz\n13\n14\nFizzBuzz\n",
        "is_sample": true,
        "label": "Reaches first FizzBuzz"
      },
      {
        "seq": 3,
        "input": "1\n",
        "expected": "1\n",
        "is_sample": false,
        "label": "Minimal boundary N=1"
      },
      {
        "seq": 4,
        "input": "2\n",
        "expected": "1\n2\n",
        "is_sample": false,
        "label": "No replacements yet"
      },
      {
        "seq": 5,
        "input": "3\n",
        "expected": "1\n2\nFizz\n",
        "is_sample": false,
        "label": "First Fizz exactly"
      },
      {
        "seq": 6,
        "input": "9\n",
        "expected": "1\n2\nFizz\n4\nBuzz\nFizz\n7\n8\nFizz\n",
        "is_sample": false,
        "label": "Several Fizz before a Buzz"
      },
      {
        "seq": 7,
        "input": "20\n",
        "expected": "1\n2\nFizz\n4\nBuzz\nFizz\n7\n8\nFizz\nBuzz\n11\nFizz\n13\n14\nFizzBuzz\n16\n17\nFizz\n19\nBuzz\n",
        "is_sample": false,
        "label": "Ends on a Buzz multiple"
      },
      {
        "seq": 8,
        "input": "30\n",
        "expected": "1\n2\nFizz\n4\nBuzz\nFizz\n7\n8\nFizz\nBuzz\n11\nFizz\n13\n14\nFizzBuzz\n16\n17\nFizz\n19\nBuzz\nFizz\n22\n23\nFizz\nBuzz\n26\nFizz\n28\n29\nFizzBuzz\n",
        "is_sample": false,
        "label": "Two full FizzBuzz cycles"
      },
      {
        "seq": 9,
        "input": "50\n",
        "expected": "1\n2\nFizz\n4\nBuzz\nFizz\n7\n8\nFizz\nBuzz\n11\nFizz\n13\n14\nFizzBuzz\n16\n17\nFizz\n19\nBuzz\nFizz\n22\n23\nFizz\nBuzz\n26\nFizz\n28\n29\nFizzBuzz\n31\n32\nFizz\n34\nBuzz\nFizz\n37\n38\nFizz\nBuzz\n41\nFizz\n43\n44\nFizzBuzz\n46\n47\nFizz\n49\nBuzz\n",
        "is_sample": false,
        "label": "Larger typical case"
      },
      {
        "seq": 10,
        "input": "100\n",
        "expected": "1\n2\nFizz\n4\nBuzz\nFizz\n7\n8\nFizz\nBuzz\n11\nFizz\n13\n14\nFizzBuzz\n16\n17\nFizz\n19\nBuzz\nFizz\n22\n23\nFizz\nBuzz\n26\nFizz\n28\n29\nFizzBuzz\n31\n32\nFizz\n34\nBuzz\nFizz\n37\n38\nFizz\nBuzz\n41\nFizz\n43\n44\nFizzBuzz\n46\n47\nFizz\n49\nBuzz\nFizz\n52\n53\nFizz\nBuzz\n56\nFizz\n58\n59\nFizzBuzz\n61\n62\nFizz\n64\nBuzz\nFizz\n67\n68\nFizz\nBuzz\n71\nFizz\n73\n74\nFizzBuzz\n76\n77\nFizz\n79\nBuzz\nFizz\n82\n83\nFizz\nBuzz\n86\nFizz\n88\n89\nFizzBuzz\n91\n92\nFizz\n94\nBuzz\nFizz\n97\n98\nFizz\nBuzz\n",
        "is_sample": false,
        "label": "N=100 boundary"
      }
    ],
    "acceptance_rate": 0.79,
    "likes": 420,
    "dislikes": 14
  },
  {
    "slug": "max-of-list",
    "problem_id": 5,
    "title": "Maximum Element",
    "difficulty": "Easy",
    "tags": [
      "Array"
    ],
    "description": "The first line contains `N`. The second line contains `N` space-separated integers. Print the maximum.",
    "constraints": [
      "1 ≤ N ≤ 10^5",
      "-10^9 ≤ a[i] ≤ 10^9"
    ],
    "examples": [
      {
        "input": "5\n3 1 4 1 5",
        "output": "5"
      },
      {
        "input": "3\n-2 -5 -1",
        "output": "-1"
      }
    ],
    "hints": [
      "A single linear scan tracking the best-so-far suffices.",
      "Don't seed the max with 0 — values can be negative. Use the first element."
    ],
    "editorial": "`max(map(int, ...))` scans once in O(n). Be careful never to initialise the running maximum to 0; negatives would break it.",
    "approach": "## Idea\n\nThe task is to find the single largest value in a list of integers. A maximum is simply the element that is greater than or equal to every other element, so a single pass over the data is enough: keep a running \"best so far\" and update it whenever you encounter a larger element.\n\n## Implementation\n\nAfter reading `N`, read the second line, split it on whitespace, and convert each token to an `int`. Python's built-in `max` does the linear scan for you, so the whole solution collapses to:\n\n```python\ninput()                              # consume N (not needed for the logic)\nprint(max(map(int, input().split())))\n```\n\nUsing `map(int, ...)` is memory-friendly because it streams the conversion lazily into `max` rather than materializing a separate list.\n\n## Things to watch\n\n- Values can be negative and as large as `1e9` in magnitude — do not initialize your running maximum to `0` or `-1`; start it at the first element (or use `float('-inf')`). Python integers are arbitrary precision, so overflow is not a concern here.\n- `N` can be up to `100000`, so the input line is large; reading it in one `split()` call and avoiding per-element printing keeps it well within the time limit.",
    "complexity": {
      "time": "O(n)",
      "space": "O(1)"
    },
    "company_tags": [
      "Amazon",
      "Google",
      "Microsoft"
    ],
    "frequency": 58,
    "related": [
      "sum-of-list",
      "binary-search",
      "two-sum-int"
    ],
    "time_limit_ms": 1500,
    "memory_limit_mb": 256,
    "checker_type": "trimmed",
    "starter": {
      "python3": "n = int(input())\nnums = list(map(int, input().split()))\n# TODO: compute the maximum element of nums\nprint(\"\")\n"
    },
    "solution": {
      "python3": "input()\nprint(max(map(int, input().split())))\n"
    },
    "test_cases": [
      {
        "seq": 1,
        "input": "5\n3 1 4 1 5\n",
        "expected": "5\n",
        "is_sample": true,
        "label": "Typical positives"
      },
      {
        "seq": 2,
        "input": "3\n-2 -5 -1\n",
        "expected": "-1\n",
        "is_sample": true,
        "label": "All negative"
      },
      {
        "seq": 3,
        "input": "1\n0\n",
        "expected": "0\n",
        "is_sample": false,
        "label": "Minimal: single zero"
      },
      {
        "seq": 4,
        "input": "1\n1000000000\n",
        "expected": "1000000000\n",
        "is_sample": false,
        "label": "Single max boundary"
      },
      {
        "seq": 5,
        "input": "1\n-1000000000\n",
        "expected": "-1000000000\n",
        "is_sample": false,
        "label": "Single min boundary"
      },
      {
        "seq": 6,
        "input": "4\n7 7 7 7\n",
        "expected": "7\n",
        "is_sample": false,
        "label": "All duplicates"
      },
      {
        "seq": 7,
        "input": "6\n-1000000000 1000000000 0 5 -5 999999999\n",
        "expected": "1000000000\n",
        "is_sample": false,
        "label": "Mixed extremes"
      },
      {
        "seq": 8,
        "input": "8\n-3 -1 -4 -1 -5 -9 -2 -6\n",
        "expected": "-1\n",
        "is_sample": false,
        "label": "Negatives, duplicate max"
      },
      {
        "seq": 9,
        "input": "2\n42 -42\n",
        "expected": "42\n",
        "is_sample": false,
        "label": "Positive vs negative pair"
      },
      {
        "seq": 10,
        "input": "100\n1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96 97 98 99 1000000000\n",
        "expected": "1000000000\n",
        "is_sample": false,
        "label": "Planted maximum among 100"
      },
      {
        "seq": 11,
        "input": "100\n-1 -2 -3 -4 -5 -6 -7 -8 -9 -10 -11 -12 -13 -14 -15 -16 -17 -18 -19 -20 -21 -22 -23 -24 -25 -26 -27 -28 -29 -30 -31 -32 -33 -34 -35 -36 -37 -38 -39 -40 -41 -42 -43 -44 -45 -46 -47 -48 -49 -50 -51 -52 -53 -54 -55 -56 -57 -58 -59 -60 -61 -62 -63 -64 -65 -66 -67 -68 -69 -70 -71 -72 -73 -74 -75 -76 -77 -78 -79 -80 -81 -82 -83 -84 -85 -86 -87 -88 -89 -90 -91 -92 -93 -94 -95 -96 -97 -98 -99 -100\n",
        "expected": "-1\n",
        "is_sample": false,
        "label": "100 descending negatives"
      }
    ],
    "acceptance_rate": 0.93,
    "likes": 310,
    "dislikes": 4
  },
  {
    "slug": "factorial",
    "problem_id": 6,
    "title": "Factorial",
    "difficulty": "Easy",
    "tags": [
      "Math",
      "Recursion"
    ],
    "description": "Print `N!` (the factorial of `N`).",
    "constraints": [
      "0 ≤ N ≤ 20"
    ],
    "examples": [
      {
        "input": "5",
        "output": "120",
        "explanation": "5 × 4 × 3 × 2 × 1 = 120"
      },
      {
        "input": "0",
        "output": "1",
        "explanation": "0! = 1 by convention"
      }
    ],
    "hints": [
      "`math.factorial(n)` is exact and handles 0.",
      "A loop `result *= i` for i in 2..N also works; it yields 1 for N=0 or 1."
    ],
    "editorial": "`math.factorial` is implemented in C and handles the 0! = 1 case. Python big-ints represent 20! exactly even though it exceeds 32-bit range.",
    "approach": "## Idea\n\nThe factorial of a non-negative integer `N`, written `N!`, is the product of all integers from `1` to `N`, with the special case `0! = 1`. So `5! = 5 * 4 * 3 * 2 * 1 = 120`. The task is simply to read `N` and print this product.\n\n## Computing it\n\nThe cleanest way in Python is to use the standard library:\n\n```python\nimport math\nprint(math.factorial(int(input())))\n```\n\n`math.factorial` handles the `0! = 1` edge case for you and is implemented in C, so it is fast and exact. Python integers are arbitrary-precision, so even `20! = 2432902008176640000` (which overflows a 32-bit and just fits a 64-bit signed integer) is represented exactly with no special handling.\n\n## Doing it manually\n\nIf you want to write the loop yourself, accumulate a running product starting at `1`:\n\n```python\nn = int(input())\nresult = 1\nfor i in range(2, n + 1):\n    result *= i\nprint(result)\n```\n\nThe loop naturally produces `1` when `n` is `0` or `1` because `range(2, n+1)` is empty. A recursive formulation (`fact(n) = n * fact(n-1)`, `fact(0) = 1`) also works since `N` is at most 20, well within Python's recursion limit. With the constraint `N <= 20`, performance is never an issue.",
    "complexity": {
      "time": "O(n)",
      "space": "O(1)"
    },
    "company_tags": [
      "Amazon",
      "Microsoft",
      "Google",
      "Adobe"
    ],
    "frequency": 62,
    "related": [
      "fibonacci",
      "sum-of-list",
      "binary-search"
    ],
    "time_limit_ms": 1000,
    "memory_limit_mb": 128,
    "checker_type": "trimmed",
    "starter": {
      "python3": "n = int(input())\n# TODO: compute n! (the factorial of n)\nprint(\"\")\n"
    },
    "solution": {
      "python3": "import math\nprint(math.factorial(int(input())))\n"
    },
    "test_cases": [
      {
        "seq": 1,
        "input": "5\n",
        "expected": "120\n",
        "is_sample": true,
        "label": "5! = 120"
      },
      {
        "seq": 2,
        "input": "0\n",
        "expected": "1\n",
        "is_sample": true,
        "label": "0! = 1"
      },
      {
        "seq": 3,
        "input": "1\n",
        "expected": "1\n",
        "is_sample": false,
        "label": "1! = 1"
      },
      {
        "seq": 4,
        "input": "2\n",
        "expected": "2\n",
        "is_sample": false,
        "label": "2! = 2"
      },
      {
        "seq": 5,
        "input": "3\n",
        "expected": "6\n",
        "is_sample": false,
        "label": "3! = 6"
      },
      {
        "seq": 6,
        "input": "7\n",
        "expected": "5040\n",
        "is_sample": false,
        "label": "7!"
      },
      {
        "seq": 7,
        "input": "10\n",
        "expected": "3628800\n",
        "is_sample": false,
        "label": "10!"
      },
      {
        "seq": 8,
        "input": "12\n",
        "expected": "479001600\n",
        "is_sample": false,
        "label": "12! near 32-bit"
      },
      {
        "seq": 9,
        "input": "13\n",
        "expected": "6227020800\n",
        "is_sample": false,
        "label": "13! exceeds 32-bit"
      },
      {
        "seq": 10,
        "input": "15\n",
        "expected": "1307674368000\n",
        "is_sample": false,
        "label": "15!"
      },
      {
        "seq": 11,
        "input": "18\n",
        "expected": "6402373705728000\n",
        "is_sample": false,
        "label": "18!"
      },
      {
        "seq": 12,
        "input": "20\n",
        "expected": "2432902008176640000\n",
        "is_sample": false,
        "label": "20! near 64-bit limit"
      }
    ],
    "acceptance_rate": 0.86,
    "likes": 295,
    "dislikes": 6
  },
  {
    "slug": "palindrome-check",
    "problem_id": 7,
    "title": "Palindrome Check",
    "difficulty": "Easy",
    "tags": [
      "String",
      "Two Pointers"
    ],
    "description": "Print `YES` if the string reads the same forwards and backwards, otherwise `NO`. The check is case-sensitive and counts every character (including spaces and punctuation).",
    "constraints": [
      "1 ≤ |s| ≤ 10^5"
    ],
    "examples": [
      {
        "input": "racecar",
        "output": "YES"
      },
      {
        "input": "hello",
        "output": "NO"
      }
    ],
    "hints": [
      "Compare `s` with `s[::-1]`.",
      "Two pointers from both ends is an O(1)-extra-space alternative."
    ],
    "editorial": "`s == s[::-1]` is the one-liner. The comparison short-circuits at the first mismatch, so non-palindromes are detected quickly.",
    "approach": "## Idea\n\nA string is a palindrome when it reads identically forwards and backwards. The most direct way to test this in Python is to compare the string against its reverse. The slice `s[::-1]` produces a new string with the characters in reverse order, and `s == s[::-1]` is `True` exactly when `s` is a palindrome.\n\n```python\ns = input()\nprint('YES' if s == s[::-1] else 'NO')\n```\n\n## Why it works\n\nBuilding the reversed copy and comparing is `O(n)` in both time and space, which is well within the 1.5s limit even for the maximum length of 100000 characters. The comparison itself short-circuits: Python stops at the first mismatched character, so non-palindromes that differ early are detected almost instantly.\n\n## Notes on this problem\n\n- The check is performed on the **raw** string exactly as given. Spaces, punctuation, and letter case all count. So `\"A man a plan a canal Panama\"` is **not** a palindrome here (the spaces and capital letters break the symmetry), and `\"Aa\"` is **not** a palindrome because `'A' != 'a'`.\n- A constant-space alternative is the two-pointer technique: walk an index `i` from the front and `j` from the back, comparing `s[i]` with `s[j]` and moving inward until they cross. This avoids allocating the reversed copy and reduces space to `O(1)`, but the slice approach is simpler and fast enough here.\n- A single character (or any input of length 1) is trivially a palindrome.",
    "complexity": {
      "time": "O(n)",
      "space": "O(n)"
    },
    "company_tags": [
      "Amazon",
      "Microsoft",
      "Google",
      "Facebook",
      "Adobe"
    ],
    "frequency": 72,
    "related": [
      "reverse-string",
      "anagram-check",
      "valid-parentheses"
    ],
    "time_limit_ms": 1500,
    "memory_limit_mb": 256,
    "checker_type": "trimmed",
    "starter": {
      "python3": "s = input()\n\n# TODO: determine whether s reads the same forwards and backwards\n# Print \"YES\" if it is a palindrome, otherwise \"NO\"\nprint(\"\")\n"
    },
    "solution": {
      "python3": "s = input()\nprint('YES' if s == s[::-1] else 'NO')\n"
    },
    "test_cases": [
      {
        "seq": 1,
        "input": "racecar\n",
        "expected": "YES\n",
        "is_sample": true,
        "label": "Odd-length palindrome"
      },
      {
        "seq": 2,
        "input": "hello\n",
        "expected": "NO\n",
        "is_sample": true,
        "label": "Not a palindrome"
      },
      {
        "seq": 3,
        "input": "a\n",
        "expected": "YES\n",
        "is_sample": false,
        "label": "Minimal single character"
      },
      {
        "seq": 4,
        "input": "ab\n",
        "expected": "NO\n",
        "is_sample": false,
        "label": "Smallest non-palindrome"
      },
      {
        "seq": 5,
        "input": "aa\n",
        "expected": "YES\n",
        "is_sample": false,
        "label": "Even-length palindrome"
      },
      {
        "seq": 6,
        "input": "A man a plan a canal Panama\n",
        "expected": "NO\n",
        "is_sample": false,
        "label": "Spaces and case matter"
      },
      {
        "seq": 7,
        "input": "Aa\n",
        "expected": "NO\n",
        "is_sample": false,
        "label": "Case-sensitive: A ≠ a"
      },
      {
        "seq": 8,
        "input": "ab,ba\n",
        "expected": "YES\n",
        "is_sample": false,
        "label": "Special characters palindrome"
      },
      {
        "seq": 9,
        "input": "a,ba\n",
        "expected": "NO\n",
        "is_sample": false,
        "label": "Special characters non-palindrome"
      },
      {
        "seq": 10,
        "input": "noon\n",
        "expected": "YES\n",
        "is_sample": false,
        "label": "Typical even palindrome"
      },
      {
        "seq": 11,
        "input": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxyxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx\n",
        "expected": "YES\n",
        "is_sample": false,
        "label": "101-char palindrome"
      },
      {
        "seq": 12,
        "input": "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaab\n",
        "expected": "NO\n",
        "is_sample": false,
        "label": "100-char near-miss"
      }
    ],
    "acceptance_rate": 0.84,
    "likes": 380,
    "dislikes": 7
  },
  {
    "slug": "binary-search",
    "problem_id": 8,
    "title": "First Occurrence (Binary Search)",
    "difficulty": "Medium",
    "tags": [
      "Array",
      "Binary Search"
    ],
    "description": "The first line contains `N` and a target `T`. The second line contains `N` integers sorted ascending. Print the smallest 1-indexed `i` with `a[i] = T`, or `-1` if `T` is absent.",
    "constraints": [
      "1 ≤ N ≤ 10^6",
      "The array is sorted in non-decreasing order."
    ],
    "examples": [
      {
        "input": "5 4\n1 3 4 7 9",
        "output": "3"
      },
      {
        "input": "4 5\n2 4 6 8",
        "output": "-1"
      }
    ],
    "hints": [
      "`bisect_left` finds the leftmost insertion point of T.",
      "If that index is in range and equals T, return index+1; else -1."
    ],
    "editorial": "Use a lower-bound search (`bisect_left`). On a match keep moving left so duplicates return the FIRST occurrence. Remember the answer is 1-indexed.",
    "approach": "## Idea\n\nThe array is given in ascending sorted order, which is the precondition that makes binary search applicable. We do not just need *any* index where the value equals `T` — we need the **first (smallest) occurrence**. With duplicates present, a plain binary search could land on any matching index, so we specifically search for the **leftmost** position where `T` could be inserted while keeping the array sorted.\n\n## Lower bound (bisect_left)\n\n`bisect.bisect_left(a, t)` returns the smallest index `i` such that every element to its left is strictly less than `T`. Two outcomes:\n\n- If `i < n` and `a[i] == t`, then `i` is the 0-indexed first occurrence, so we print `i + 1` to convert to the required 1-indexed answer.\n- Otherwise `T` is absent (either `i` ran past the end, or `a[i]` is a value greater than `T`), so we print `-1`.\n\nThis naturally handles all edge cases: a target smaller than everything yields `i = 0` with `a[0] != t`; a target larger than everything yields `i = n`; and a run of equal values returns the index of the first one.\n\n## Implementing it by hand\n\nIf you cannot use `bisect`, run the classic lower-bound loop:\n\n```python\nlo, hi = 0, n  # search in [lo, hi)\nwhile lo < hi:\n    mid = (lo + hi) // 2\n    if a[mid] < t:\n        lo = mid + 1\n    else:\n        hi = mid\n# lo is the first index >= t\n```\n\nThe key detail versus a naive search is that on a match you keep moving `hi` left rather than returning immediately, so you converge on the *first* equal element instead of an arbitrary one.",
    "complexity": {
      "time": "O(log n)",
      "space": "O(1)"
    },
    "company_tags": [
      "Amazon",
      "Google",
      "Microsoft",
      "Bloomberg",
      "Adobe"
    ],
    "frequency": 78,
    "related": [
      "two-sum-int",
      "longest-increasing-subseq",
      "max-of-list"
    ],
    "time_limit_ms": 2000,
    "memory_limit_mb": 256,
    "checker_type": "trimmed",
    "starter": {
      "python3": "n, t = map(int, input().split())\na = list(map(int, input().split()))\n# TODO: find the smallest 1-indexed i such that a[i] == t, or -1 if t is absent\nprint(\"\")\n"
    },
    "solution": {
      "python3": "import bisect\nn, t = map(int, input().split())\na = list(map(int, input().split()))\ni = bisect.bisect_left(a, t)\nprint(i + 1 if i < n and a[i] == t else -1)\n"
    },
    "test_cases": [
      {
        "seq": 1,
        "input": "5 4\n1 3 4 7 9\n",
        "expected": "3\n",
        "is_sample": true,
        "label": "Target present, unique"
      },
      {
        "seq": 2,
        "input": "4 5\n2 4 6 8\n",
        "expected": "-1\n",
        "is_sample": true,
        "label": "Target absent"
      },
      {
        "seq": 3,
        "input": "1 7\n7\n",
        "expected": "1\n",
        "is_sample": false,
        "label": "Single element, present"
      },
      {
        "seq": 4,
        "input": "1 7\n3\n",
        "expected": "-1\n",
        "is_sample": false,
        "label": "Single element, absent"
      },
      {
        "seq": 5,
        "input": "7 5\n1 5 5 5 5 8 9\n",
        "expected": "2\n",
        "is_sample": false,
        "label": "Duplicates, first occurrence"
      },
      {
        "seq": 6,
        "input": "6 -3\n-3 0 0 2 4 4\n",
        "expected": "1\n",
        "is_sample": false,
        "label": "Target at first position (negative)"
      },
      {
        "seq": 7,
        "input": "6 100\n1 2 3 50 99 100\n",
        "expected": "6\n",
        "is_sample": false,
        "label": "Target at last position"
      },
      {
        "seq": 8,
        "input": "5 0\n1 2 3 4 5\n",
        "expected": "-1\n",
        "is_sample": false,
        "label": "Target below all values"
      },
      {
        "seq": 9,
        "input": "8 -2\n-9 -2 -2 -2 0 3 3 10\n",
        "expected": "2\n",
        "is_sample": false,
        "label": "Negatives with duplicate run"
      },
      {
        "seq": 10,
        "input": "5 4\n4 4 4 4 4\n",
        "expected": "1\n",
        "is_sample": false,
        "label": "All identical equal to target"
      },
      {
        "seq": 11,
        "input": "128 100\n1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96 97 98 99 100 101 102 103 104 105 106 107 108 109 110 111 112 113 114 115 116 117 118 119 120 121 122 123 124 125 126 127 128\n",
        "expected": "100\n",
        "is_sample": false,
        "label": "128 sorted, target present"
      },
      {
        "seq": 12,
        "input": "128 200\n1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96 97 98 99 100 101 102 103 104 105 106 107 108 109 110 111 112 113 114 115 116 117 118 119 120 121 122 123 124 125 126 127 128\n",
        "expected": "-1\n",
        "is_sample": false,
        "label": "128 sorted, target absent"
      }
    ],
    "acceptance_rate": 0.62,
    "likes": 540,
    "dislikes": 21
  },
  {
    "slug": "anagram-check",
    "problem_id": 9,
    "title": "Anagram Check",
    "difficulty": "Medium",
    "tags": [
      "String",
      "Hash Table",
      "Sorting"
    ],
    "description": "Two strings are given on two lines. Print `YES` if they are anagrams (the same multiset of characters), else `NO`. The check is case-sensitive and counts spaces and punctuation.",
    "constraints": [
      "1 ≤ |a|, |b| ≤ 10^5"
    ],
    "examples": [
      {
        "input": "listen\nsilent",
        "output": "YES"
      },
      {
        "input": "hello\nbello",
        "output": "NO"
      }
    ],
    "hints": [
      "Compare `collections.Counter` of each string.",
      "Sorting both and comparing also works in O(n log n)."
    ],
    "editorial": "`Counter(a) == Counter(b)` compares character multiplicities in O(n). Strings of different lengths can never be anagrams.",
    "approach": "## Idea\n\nTwo strings are anagrams when they contain exactly the same characters with the same multiplicities, just possibly in a different order. So the order of characters is irrelevant; only the *count* of each distinct character matters. This immediately gives two clean strategies: compare sorted versions of the strings, or compare character-frequency tables.\n\n## Frequency-count solution (used here)\n\nBuild a frequency map (a multiset) for each string and check whether the two maps are equal. Python's `collections.Counter` does exactly this, and `Counter(a) == Counter(b)` is `True` only when both strings have identical character counts.\n\n```python\nfrom collections import Counter\na = input(); b = input()\nprint('YES' if Counter(a) == Counter(b) else 'NO')\n```\n\nThis runs in `O(n)` time since each string is scanned once and dictionary equality compares at most the number of distinct characters.\n\n## Key details for THIS problem\n\n- The comparison is **case-sensitive** and treats every character literally: `\"Tea\"` and `\"Eat\"` are NOT anagrams because `T != t` and `E != e`.\n- **Whitespace and punctuation count as characters.** `\"dormitory \"` and `\"dirty room\"` are anagrams only because both contain the same single space plus the same letters.\n- Two **empty** strings are anagrams (both have an empty multiset), so the answer is `YES`.\n- Strings of **different lengths** can never be anagrams.\n\n## Alternative\n\nSorting both strings and comparing — `sorted(a) == sorted(b)` — is equally correct but costs `O(n log n)`. The counting approach is preferred for large inputs because it is linear.",
    "complexity": {
      "time": "O(n)",
      "space": "O(k) where k is the number of distinct characters (O(1) for a fixed alphabet)"
    },
    "company_tags": [
      "Amazon",
      "Microsoft",
      "Google",
      "Facebook",
      "Bloomberg"
    ],
    "frequency": 78,
    "related": [
      "palindrome-check",
      "reverse-string",
      "valid-parentheses"
    ],
    "time_limit_ms": 2000,
    "memory_limit_mb": 256,
    "checker_type": "trimmed",
    "starter": {
      "python3": "a = input()\nb = input()\n# TODO: determine whether a and b are anagrams (same multiset of characters)\n# Print \"YES\" if they are, otherwise \"NO\"\nprint(\"\")\n"
    },
    "solution": {
      "python3": "from collections import Counter\na = input()\nb = input()\nprint('YES' if Counter(a) == Counter(b) else 'NO')\n"
    },
    "test_cases": [
      {
        "seq": 1,
        "input": "listen\nsilent\n",
        "expected": "YES\n",
        "is_sample": true,
        "label": "Classic anagram"
      },
      {
        "seq": 2,
        "input": "hello\nbello\n",
        "expected": "NO\n",
        "is_sample": true,
        "label": "One character differs"
      },
      {
        "seq": 3,
        "input": "\n\n",
        "expected": "YES\n",
        "is_sample": false,
        "label": "Both empty strings"
      },
      {
        "seq": 4,
        "input": "a\nb\n",
        "expected": "NO\n",
        "is_sample": false,
        "label": "Single different chars"
      },
      {
        "seq": 5,
        "input": "a\na\n",
        "expected": "YES\n",
        "is_sample": false,
        "label": "Single identical chars"
      },
      {
        "seq": 6,
        "input": "aabbcc\nabcabc\n",
        "expected": "YES\n",
        "is_sample": false,
        "label": "Reordered with duplicates"
      },
      {
        "seq": 7,
        "input": "aab\nabb\n",
        "expected": "NO\n",
        "is_sample": false,
        "label": "Same letters, different counts"
      },
      {
        "seq": 8,
        "input": "Tea\nEat\n",
        "expected": "NO\n",
        "is_sample": false,
        "label": "Case-sensitive mismatch"
      },
      {
        "seq": 9,
        "input": "dormitory \ndirty room\n",
        "expected": "YES\n",
        "is_sample": false,
        "label": "Spaces count as characters"
      },
      {
        "seq": 10,
        "input": "a1b2c3!@#\n#@!3c2b1a\n",
        "expected": "YES\n",
        "is_sample": false,
        "label": "Digits and special characters"
      },
      {
        "seq": 11,
        "input": "abc\nabcd\n",
        "expected": "NO\n",
        "is_sample": false,
        "label": "Different lengths"
      },
      {
        "seq": 12,
        "input": "abababababababababababababababababababababababababababababababababababababababababababababababababab\nbabababababababababababababababababababababababababababababababababababababababababababababababababa\n",
        "expected": "YES\n",
        "is_sample": false,
        "label": "100-char anagram"
      },
      {
        "seq": 13,
        "input": "abababababababababababababababababababababababababababababababababababababababababababababababababab\nabababababababababababababababababababababababababababababababababababababababababababababababababcc\n",
        "expected": "NO\n",
        "is_sample": false,
        "label": "100-char non-anagram"
      }
    ],
    "acceptance_rate": 0.68,
    "likes": 470,
    "dislikes": 19
  },
  {
    "slug": "fibonacci",
    "problem_id": 10,
    "title": "Nth Fibonacci",
    "difficulty": "Medium",
    "tags": [
      "Dynamic Programming",
      "Math",
      "Recursion"
    ],
    "description": "Print the Nth Fibonacci number, where F(0) = 0 and F(1) = 1.",
    "constraints": [
      "0 ≤ N ≤ 90 (the result fits in a 64-bit signed integer)."
    ],
    "examples": [
      {
        "input": "10",
        "output": "55"
      },
      {
        "input": "0",
        "output": "0"
      }
    ],
    "hints": [
      "Iterate `a, b = b, a + b` N times — O(N) time, O(1) space.",
      "Naive recursion is exponential; don't."
    ],
    "editorial": "Bottom-up DP keeping only the last two values. After N steps `a` holds F(N). F(90) fits in 64 bits.",
    "approach": "## Idea\n\nThe Fibonacci sequence is defined by `F(0) = 0`, `F(1) = 1`, and `F(n) = F(n-1) + F(n-2)` for `n >= 2`. A naive recursive implementation recomputes the same subproblems exponentially many times (`O(2^n)`), which is far too slow. The key insight is that to compute the next number you only ever need the **previous two values**, so the whole sequence can be built bottom-up in a single linear pass.\n\n## Iterative bottom-up\n\nKeep two running variables, `a` and `b`, holding `F(i)` and `F(i+1)`. Starting from `a, b = 0, 1` (i.e. `F(0)` and `F(1)`), repeatedly update them with the simultaneous assignment:\n\n```python\na, b = b, a + b\n```\n\nAfter `n` such steps, `a` holds `F(n)`. This uses only constant extra memory and runs in linear time.\n\n## Why no overflow concerns\n\nThe input is bounded by `N <= 90`, and `F(90) = 2880067194370816120`. Python integers have arbitrary precision, so the result is always exact with no special big-integer handling required. The same logic in fixed-width languages would need 64-bit integers, since `F(90)` exceeds the 32-bit range but fits in a signed 64-bit integer.",
    "complexity": {
      "time": "O(n)",
      "space": "O(1)"
    },
    "company_tags": [
      "Amazon",
      "Google",
      "Microsoft",
      "Apple",
      "Adobe"
    ],
    "frequency": 78,
    "related": [
      "factorial",
      "longest-increasing-subseq",
      "sum-of-list"
    ],
    "time_limit_ms": 1500,
    "memory_limit_mb": 128,
    "checker_type": "trimmed",
    "starter": {
      "python3": "n = int(input())\n# TODO: compute F(n), where F(0)=0, F(1)=1, F(n)=F(n-1)+F(n-2)\nprint(\"\")\n"
    },
    "solution": {
      "python3": "n = int(input())\na, b = 0, 1\nfor _ in range(n):\n    a, b = b, a + b\nprint(a)\n"
    },
    "test_cases": [
      {
        "seq": 1,
        "input": "0\n",
        "expected": "0\n",
        "is_sample": true,
        "label": "Base case F(0)"
      },
      {
        "seq": 2,
        "input": "1\n",
        "expected": "1\n",
        "is_sample": true,
        "label": "Base case F(1)"
      },
      {
        "seq": 3,
        "input": "2\n",
        "expected": "1\n",
        "is_sample": false,
        "label": "F(2) = F(0)+F(1)"
      },
      {
        "seq": 4,
        "input": "7\n",
        "expected": "13\n",
        "is_sample": false,
        "label": "Small typical case"
      },
      {
        "seq": 5,
        "input": "10\n",
        "expected": "55\n",
        "is_sample": false,
        "label": "Typical case"
      },
      {
        "seq": 6,
        "input": "20\n",
        "expected": "6765\n",
        "is_sample": false,
        "label": "Medium case"
      },
      {
        "seq": 7,
        "input": "30\n",
        "expected": "832040\n",
        "is_sample": false,
        "label": "Larger case"
      },
      {
        "seq": 8,
        "input": "50\n",
        "expected": "12586269025\n",
        "is_sample": false,
        "label": "Exceeds 32-bit range"
      },
      {
        "seq": 9,
        "input": "75\n",
        "expected": "2111485077978050\n",
        "is_sample": false,
        "label": "Large value"
      },
      {
        "seq": 10,
        "input": "90\n",
        "expected": "2880067194370816120\n",
        "is_sample": false,
        "label": "Max boundary N=90"
      }
    ],
    "acceptance_rate": 0.71,
    "likes": 880,
    "dislikes": 12
  },
  {
    "slug": "valid-parentheses",
    "problem_id": 11,
    "title": "Valid Parentheses",
    "difficulty": "Medium",
    "tags": [
      "Stack",
      "String"
    ],
    "description": "A string contains only the characters `()[]{}`. Print `YES` if every opening bracket has a matching closing bracket in the correct order, otherwise `NO`.",
    "constraints": [
      "1 ≤ |s| ≤ 10^5"
    ],
    "examples": [
      {
        "input": "()",
        "output": "YES"
      },
      {
        "input": "([)]",
        "output": "NO"
      }
    ],
    "hints": [
      "Push openers on a stack; on a closer, pop and check it matches.",
      "After the scan the stack must be empty, or some opener was never closed."
    ],
    "editorial": "A stack models the last-opened-first-closed rule. Map each closer to its opener; reject on mismatch or empty stack, and require an empty stack at the end.",
    "approach": "## Idea\n\nA bracket sequence is valid only when every closing bracket matches the *most recently opened* bracket that is still unclosed. That \"most recent, first to close\" behavior is exactly the Last-In-First-Out discipline of a **stack**.\n\n## Algorithm\n\nScan the string left to right while maintaining a stack of unmatched opening brackets:\n\n- When you see an opener (`(`, `[`, `{`), push it.\n- When you see a closer (`)`, `]`, `}`), the top of the stack must be its matching opener. If the stack is empty, or the top does not match (use a map `{')':'(', ']':'[', '}':'{'}`), the string is invalid.\n\n```\nfor c in s:\n    if c is an opener: push c\n    else:\n        if stack empty or stack.pop() != match[c]: invalid\n```\n\n## Why the final check matters\n\nMatching closers as you go is not enough — a string like `(` never triggers a mismatch but is still invalid. After the scan, the stack must be **empty**; any leftover openers were never closed. Print `YES` only when no mismatch occurred *and* the stack is empty, otherwise `NO`. Each character is pushed and popped at most once, so the whole thing is a single linear pass.",
    "complexity": {
      "time": "O(n)",
      "space": "O(n)"
    },
    "company_tags": [
      "Amazon",
      "Google",
      "Microsoft",
      "Facebook",
      "Bloomberg"
    ],
    "frequency": 92,
    "related": [
      "reverse-string",
      "palindrome-check",
      "anagram-check"
    ],
    "time_limit_ms": 1500,
    "memory_limit_mb": 256,
    "checker_type": "trimmed",
    "starter": {
      "python3": "s = input()\n\n# TODO: check whether every bracket in s is matched in correct order.\n# Hint: use a stack and a mapping from each closing bracket to its opener.\nprint(\"\")\n"
    },
    "solution": {
      "python3": "s = input()\nstack = []\npairs = {')': '(', ']': '[', '}': '{'}\nok = True\nfor c in s:\n    if c in '([{':\n        stack.append(c)\n    elif not stack or stack.pop() != pairs[c]:\n        ok = False\n        break\nprint('YES' if ok and not stack else 'NO')\n"
    },
    "test_cases": [
      {
        "seq": 1,
        "input": "()\n",
        "expected": "YES\n",
        "is_sample": true,
        "label": "Simple matched pair"
      },
      {
        "seq": 2,
        "input": "([)]\n",
        "expected": "NO\n",
        "is_sample": true,
        "label": "Interleaved, wrong order"
      },
      {
        "seq": 3,
        "input": "(\n",
        "expected": "NO\n",
        "is_sample": false,
        "label": "Single unclosed opener"
      },
      {
        "seq": 4,
        "input": ")\n",
        "expected": "NO\n",
        "is_sample": false,
        "label": "Closer with empty stack"
      },
      {
        "seq": 5,
        "input": "()[]{}\n",
        "expected": "YES\n",
        "is_sample": false,
        "label": "All three pair types"
      },
      {
        "seq": 6,
        "input": "{[()]}\n",
        "expected": "YES\n",
        "is_sample": false,
        "label": "Properly nested mix"
      },
      {
        "seq": 7,
        "input": "(]\n",
        "expected": "NO\n",
        "is_sample": false,
        "label": "Mismatched closer type"
      },
      {
        "seq": 8,
        "input": "((((((((((\n",
        "expected": "NO\n",
        "is_sample": false,
        "label": "Many unclosed openers"
      },
      {
        "seq": 9,
        "input": "]\n",
        "expected": "NO\n",
        "is_sample": false,
        "label": "Single stray closer"
      },
      {
        "seq": 10,
        "input": "()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()\n",
        "expected": "YES\n",
        "is_sample": false,
        "label": "100 balanced pairs"
      },
      {
        "seq": 11,
        "input": "((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((\n",
        "expected": "NO\n",
        "is_sample": false,
        "label": "100 unclosed openers"
      },
      {
        "seq": 12,
        "input": "([{([{([{([{([{([{([{([{([{([{([{([{([{([{([{([{([{([{([{([{}])}])}])}])}])}])}])}])}])}])}])}])}])}])}])}])}])}])}])}])\n",
        "expected": "YES\n",
        "is_sample": false,
        "label": "Deeply nested balanced (120 chars)"
      }
    ],
    "acceptance_rate": 0.55,
    "likes": 1620,
    "dislikes": 35
  },
  {
    "slug": "longest-increasing-subseq",
    "problem_id": 12,
    "title": "Longest Increasing Subsequence",
    "difficulty": "Hard",
    "tags": [
      "Dynamic Programming",
      "Binary Search",
      "Array"
    ],
    "description": "The first line contains `N`. The second line contains `N` integers. Print the length of the longest STRICTLY increasing subsequence.",
    "constraints": [
      "1 ≤ N ≤ 10^5",
      "-10^9 ≤ a[i] ≤ 10^9"
    ],
    "examples": [
      {
        "input": "8\n10 9 2 5 3 7 101 18",
        "output": "4",
        "explanation": "One LIS is [2, 3, 7, 18]."
      },
      {
        "input": "5\n1 2 3 4 5",
        "output": "5"
      }
    ],
    "hints": [
      "Maintain a `tails` array; binary-search each value's slot.",
      "`bisect_left` (lower bound) enforces STRICT increase."
    ],
    "editorial": "Patience sorting: `tails[k]` is the smallest tail of an increasing run of length k+1. `bisect_left` places each value; the answer is len(tails). O(n log n).",
    "approach": "## Idea\n\nWe want the length of the longest **strictly increasing** subsequence (LIS). The classic `O(n^2)` dynamic programming solution (`dp[i]` = LIS ending at `i`) is too slow for `N` up to `1e5`. Instead we use the patience-sorting trick that runs in `O(n log n)`.\n\n## Tails array\n\nMaintain an array `tails`, where `tails[k]` is the **smallest possible tail value** of any strictly increasing subsequence of length `k+1` seen so far. This array is always sorted in increasing order. For each incoming value `x`:\n\n- Find the leftmost position `i` where `x` could replace an element using `bisect_left` (binary search). Using `bisect_left` (lower bound) is what enforces *strict* increase: an equal value lands on the existing entry and overwrites it rather than extending the run.\n- If `i == len(tails)`, then `x` is larger than every tail, so it extends the best subsequence: append it.\n- Otherwise, overwrite `tails[i] = x`, keeping the tail for that length as small as possible so future elements have more room to extend.\n\nThe final answer is simply `len(tails)`.\n\n## Why it works\n\n`tails` is not itself a valid subsequence, but its **length** always equals the current LIS length. Each element triggers one binary search and one constant-time update, giving `O(n log n)` overall. Note this returns the LIS *length*, not the subsequence itself; to recover the actual sequence you would store parent pointers, but that is not required here.",
    "complexity": {
      "time": "O(n log n)",
      "space": "O(n)"
    },
    "company_tags": [
      "Google",
      "Microsoft",
      "Amazon",
      "Meta",
      "Bloomberg"
    ],
    "frequency": 82,
    "related": [
      "binary-search",
      "fibonacci",
      "max-of-list"
    ],
    "time_limit_ms": 3000,
    "memory_limit_mb": 256,
    "checker_type": "trimmed",
    "starter": {
      "python3": "n = int(input())\na = list(map(int, input().split()))\n# TODO: compute the length of the longest STRICTLY increasing subsequence\nprint(\"\")\n"
    },
    "solution": {
      "python3": "from bisect import bisect_left\ninput()\na = list(map(int, input().split()))\ntails = []\nfor x in a:\n    i = bisect_left(tails, x)\n    if i == len(tails):\n        tails.append(x)\n    else:\n        tails[i] = x\nprint(len(tails))\n"
    },
    "test_cases": [
      {
        "seq": 1,
        "input": "8\n10 9 2 5 3 7 101 18\n",
        "expected": "4\n",
        "is_sample": true,
        "label": "Typical case"
      },
      {
        "seq": 2,
        "input": "5\n1 2 3 4 5\n",
        "expected": "5\n",
        "is_sample": true,
        "label": "Already sorted"
      },
      {
        "seq": 3,
        "input": "1\n5\n",
        "expected": "1\n",
        "is_sample": false,
        "label": "Single element"
      },
      {
        "seq": 4,
        "input": "6\n9 8 7 6 5 4\n",
        "expected": "1\n",
        "is_sample": false,
        "label": "Strictly decreasing"
      },
      {
        "seq": 5,
        "input": "7\n2 2 2 3 3 1 4\n",
        "expected": "3\n",
        "is_sample": false,
        "label": "Duplicates need strict increase"
      },
      {
        "seq": 6,
        "input": "6\n-5 -3 -10 0 -1 8\n",
        "expected": "4\n",
        "is_sample": false,
        "label": "Negative numbers"
      },
      {
        "seq": 7,
        "input": "9\n0 8 4 12 2 10 6 14 1\n",
        "expected": "4\n",
        "is_sample": false,
        "label": "Interleaved values"
      },
      {
        "seq": 8,
        "input": "4\n-1000000000 1000000000 -1000000000 0\n",
        "expected": "2\n",
        "is_sample": false,
        "label": "Extreme bounds"
      },
      {
        "seq": 9,
        "input": "100\n1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96 97 98 99 100\n",
        "expected": "100\n",
        "is_sample": false,
        "label": "100 strictly increasing"
      },
      {
        "seq": 10,
        "input": "100\n7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7\n",
        "expected": "1\n",
        "is_sample": false,
        "label": "100 identical"
      },
      {
        "seq": 11,
        "input": "100\n100 99 98 97 96 95 94 93 92 91 90 89 88 87 86 85 84 83 82 81 80 79 78 77 76 75 74 73 72 71 70 69 68 67 66 65 64 63 62 61 60 59 58 57 56 55 54 53 52 51 50 49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10 9 8 7 6 5 4 3 2 1\n",
        "expected": "1\n",
        "is_sample": false,
        "label": "100 strictly decreasing"
      }
    ],
    "acceptance_rate": 0.41,
    "likes": 2240,
    "dislikes": 87
  }
];

export const PROBLEM_LISTS: ProblemList[] = [
  {
    slug: "fundamentals",
    name: "Fundamentals",
    description: "Warm-up problems that teach the judge's stdin/stdout conventions.",
    icon: "○",
    problem_slugs: ["two-sum-int", "sum-of-list", "max-of-list", "factorial", "reverse-string"],
  },
  {
    slug: "strings-101",
    name: "Strings 101",
    description: "Core string manipulation: reversal, palindromes, anagrams, matching.",
    icon: "▢",
    problem_slugs: ["reverse-string", "palindrome-check", "anagram-check", "valid-parentheses"],
  },
  {
    slug: "algorithms-essentials",
    name: "Algorithms Essentials",
    description: "Binary search, dynamic programming, and the classic LIS pattern.",
    icon: "◈",
    problem_slugs: ["binary-search", "fibonacci", "longest-increasing-subseq", "valid-parentheses"],
  },
  {
    slug: "interview-top-picks",
    name: "Interview Top Picks",
    description: "The questions most likely to show up in a coding interview.",
    icon: "★",
    problem_slugs: ["two-sum-int", "valid-parentheses", "anagram-check", "binary-search", "fibonacci", "longest-increasing-subseq"],
  },
];

export function findProblem(slug: string): Problem | undefined {
  return PROBLEMS.find((p) => p.slug === slug);
}

export function findList(slug: string): ProblemList | undefined {
  return PROBLEM_LISTS.find((l) => l.slug === slug);
}

export function listTags(): string[] {
  const s = new Set<string>();
  PROBLEMS.forEach((p) => p.tags.forEach((t) => s.add(t)));
  return Array.from(s).sort();
}

export function listCompanies(): string[] {
  const s = new Set<string>();
  PROBLEMS.forEach((p) => p.company_tags.forEach((c) => s.add(c)));
  return Array.from(s).sort();
}

export function relatedProblems(slug: string): Problem[] {
  const p = findProblem(slug);
  if (!p) return [];
  return p.related.map(findProblem).filter((x): x is Problem => Boolean(x));
}

// Deterministic "daily" pick — same problem all day, rotates by date.
export function dailyProblem(date = new Date()): Problem {
  const dayOfYear = Math.floor(
    (date.getTime() - new Date(date.getFullYear(), 0, 0).getTime()) /
      (1000 * 60 * 60 * 24),
  );
  return PROBLEMS[dayOfYear % PROBLEMS.length];
}

// Random problem, optionally excluding one slug (for a "pick another").
export function randomProblem(excludeSlug?: string): Problem {
  const pool = excludeSlug ? PROBLEMS.filter((p) => p.slug !== excludeSlug) : PROBLEMS;
  const idx = Math.floor(Math.random() * pool.length);
  return pool[idx] ?? PROBLEMS[0];
}
